export const LIST_ARTICLES_REQUEST = 'LIST_ARTICLES_REQUEST'
export const LIST_ARTICLES_SUCCESS = 'LIST_ARTICLES_SUCCESS'
export const LIST_ARTICLES_FAIL = 'LIST_ARTICLES_FAIL'

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_FAIL = 'GET_ARTICLE_FAIL'

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL'

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST'
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL'
export const UPDATE_PRODUCT_RESET='UPDATE_PRODUCT_RESET'
           

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

